dataset:
  train_csv: "data/train.csv"
  val_csv: "data/val.csv"
  train_img_dir: "data/utk_train/train"
  val_img_dir: "data/utk_val/val"

model:
  pretrained: true
  age_num_hidden: 128
  gender_num_classes: 2

training:
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 20

output:
  checkpoint_path: "checkpoints/age_gender_model.pth"
